grpc:
  server:
    port: 12345
    reflection-service-enabled: true

server:
  port: 8080

spring:
  application:
    name: video-catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mini_netflix
    driver-class-name: org.postgresql.Driver
    username: tuyenngo
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

logging:
  level:
    root: info
    net.devh.boot.grpc.server: debug